apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
 - target:
    kind: Ingress
    name: djangogirls
    namespace: default
    group: apps
    version: v1
   patch: |-
    - op: replace
      path: /spec/rules/host   
      value: "stage.eqlan.ru"

