apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - target:
      kind: Ingress
      name: djangogirls
      namespace: default
      group: networking.k8s.io
      version: v1
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "stage.eqlan.ru"

