---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  url: oci://ghcr.io/nginx/charts
  type: oci

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: 2.3.x
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 5h
  interval: 5h
  releaseName: nginx